// libs
import 'lib/angular/angular.js';
import 'lib/angular-animate/angular-animate.js';
import 'lib/angular-sanitize/angular-sanitize.js';
import 'lib/angular-ui-router/release/angular-ui-router.js';
import 'lib/ionic/js/ionic.js';
import 'lib/ionic/js/ionic-angular.js';
import 'lib/meteor-client-side/dist/meteor-client-side.bundle';
import 'lib/angular-meteor/dist/angular-meteor.bundle';
import 'lib/angular-moment/angular-moment.js';
// app
import './app';